### ISSUE TITLE
Rename `fit_transform` to `fit_and_transform`

### ISSUE THREAD

**Issue by lars-reimann** [Safe-DS/Stdlib#112]
### Is your feature request related to a problem?

The [`fit_transform`](https://github.com/Safe-DS/Stdlib/blob/b18a06dce090a1bb9b6e3c858b83cd8b6277e280/src/safeds/data/tabular/transformation/_table_transformer.py#L54) method of the `TableTransformer` class does not clearly indicate that the method 1. fits the transformer 2. transforms the data.

### Desired solution

Call it `fit_and_transform` instead.

**Comment by gantanikhilraj** [comment]
I would like to work on this issue, please assign it to me.
As of my understanding I need the replace fit_transform to fit_and_transform in every file? is that waht you mentioned.

**Comment by dev-DTECH** [comment]
I would like to work on this issue.

I understood that the method 
```python 
fit_transform(self, table: Table, column_names: Optional[list[str]] = None) -> Table
```
needs to be refactored as 
```python 
fit_and_transform(self, table: Table, column_names: Optional[list[str]] = None) -> Table
```
in [_table_transformer.py](https://github.com/Safe-DS/Stdlib/blob/b18a06dce090a1bb9b6e3c858b83cd8b6277e280/src/safeds/data/tabular/transformation/_table_transformer.py)

**Comment by gantanikhilraj** [comment]
Yes, I got it please assign it to me. I will start working on it.

**Comment by dev-DTECH** [comment]
Ok @lars-reimann can you assign the issue to me. I will do the necessary changes and make a PR.
