### ISSUE TITLE
Check that methods of `Table` can handle an empty table

### ISSUE THREAD

**Issue by lars-reimann** [Safe-DS/Stdlib#123]
The methods of `Table` should work properly on an empty table. We don't currently handle this edge case, however. An appropriate tests should be added for each method of the `Table` class.

Example: It should be possible to add any row and any column to an empty table.

**Comment by zzril** [comment]
What about the `Transformers`? Should it be possible to `fit` them on empty tables? Also, should it be possible to `transform` empty tables using them?  
(The latter one is probably always trivially possible.)
