### ISSUE TITLE
Check that methods of `Table` update the schema properly

### ISSUE THREAD

**Issue by lars-reimann** [Safe-DS/Stdlib#124]
At best, the existing tests of the methods that return a new `Table` check whether this new `Table` has the correct data. We must also ensure that its schema is correct. This needs more tests.

**Comment by lars-reimann** [comment]
Should be done after #98.

**Comment by zzril** [comment]
There should be a dedicated test for testing that the schema has been set up properly for a new `Table`.

This could be done in a new test, or inside of `tests/safeds/data/tabular/containers/table/test_column_names.py` (which currently seems to be responsible for testing the `Table` constructor method).
