### ISSUE TITLE
A function which drops all non numerical columns 

### ISSUE THREAD

**Issue by Gerhardsa0** [Safe-DS/Stdlib#13]
### Is your feature request related to a problem? Please describe

Sometimes we want to drop all non numerical columns, so we can easily plot an heatmap.
A function which drops all non numerical rows and returns a new table could work well here.

### Desired solution

```Table.drop_non_numerical_columns()```-->```Table```

**Comment by lars-reimann** [comment]
The transformation can already be achieved by writing `Table.from_columns(table.list_columns_with_non_numerical_values())`. For the plotting methods we should maybe offer a parameter to decide whether to raise an exception when invalid columns are passed or whether to ignore them.

**Comment by lars-reimann** [comment]
This is done now:

* `correlation_heatmap` now can be called on a `Table` with some non-numerical columns (#92).
* `boxplot` and `histogram` are called directly on a `Column`, so raising an exception makes sense.
* `lineplot` and `scatterplot` are called on a `Table` but columns are specified explicitly by their name. Raising an exception again makes sense.
