### ISSUE TITLE
Discretize `Table`

### ISSUE THREAD

**Issue by lars-reimann** [Safe-DS/Stdlib#143]
### Is your feature request related to a problem?

Discretization means to replace a continuous variable by a variable that only has a finite amount of values. This is a preprocessing step that we should support.

### Desired solution

* Add a class `Discretizer` in `safeds.data.tabular.transformation` that wraps the [`KBinsDiscretizer` of `scikit-learn`](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.KBinsDiscretizer.html)
* Make the class a subclass of `TableTransformer`
* The `__init__` should for now only have a parameter `number_of_bins` to control how many bins are created
* If `number_of_bins` is less than 2, raise a `ValueError`

**Comment by guenterk** [comment]
@robmeth : Please add a comment explaining the problem why you marked this as blocked (you mentioned in the final stand up meeting today the failing pandasEqualsTest...).

**Comment by Marsmaennchen221** [comment]
@robmeth Use the ordinal encoding. This transforms the data and returns the bin index rather than a bin as sparse matrix. This will also resolve the problem with the tests. See https://github.com/Safe-DS/Stdlib/pull/327#discussion_r1233345857
