### ISSUE TITLE
Summary from feedback round

### ISSUE THREAD

**Issue by zzril** [Safe-DS/Stdlib#182]
Make proper issues out of these:

* ~~`OneHotEncoder`: Doku etwas "abstrakt" ( -> Codebeispiele?)~~
* ~~`OneHotEncoder`: schwierig zu benutzen (Doku?), Beispiel wäre sehr gut (Referenz auf "Dummies", wie sie bei `pandas` heißen, wäre auch praktisch)~~
  * #181 
* ~~`OneHotEncoder` bzw. alle Transformer: Doku sollte klarstellen, dass Spaltennamen sich ändern; Zugriff auf neue Spaltennamen (oder gelöschte) wäre hilfreich~~
  * #190 
* ~~"Wann werden Kopien zurückgegeben, wann wird in-place gearbeitet?"~~ 
  * #189
* ~~`OneHotEncoder`: Unklar, dass er *überhaupt* zu benutzen ist (siehe unten); allgemein: Interface mit `fit`, `predict`, `transform` etc. besser klarmachen~~
  * #153 & #181
* ~~mehrfache Verwendung von `fit` (bei Klassifizierer und Transformer) evtl. ungünstig -> `Discussion`?~~
  * Würde ich für den Moment nicht ändern, da das `fit` schon die gleiche Bedeutung bei beidem hat (@lars-reimann) 
* ~~(evtl. mehr Querverweise in der Doku)~~
  * Darauf sollten wir auf jeden Fall achten. Ich finde es allerdings schwierig, das als Issue festzuhalten. Wir sollten eher unsere [Development Guidelines](https://stdlib.safe-ds.com/en/stable/development/guidelines/) erweitern.
  * #191
* ~~(Zur Poetry-Doku hinzufügen: `poetry add safe-ds`)~~
  * Für den Moment würde ich das nicht ändern. Die Personen, die `poetry` nutzen, wissen bereits wie sie damit neue Abhängigkeiten hinzufügen können. Der Verweis zu `pip` ist für die absoluten Einsteiger, die gerade Python installiert haben (@lars-reimann)
* ~~Scikit-Fehlermeldungen abfangen (und durch eigene ersetzen) (z.B., wenn nicht-numerische Daten benutzt werden -> dann in der neuen Exception direkt vorschlagen, was zu machen ist)~~
  * #153
* ~~Doku / Codebeispiel zum `OneHotEncoder` sagt verwirrenderweise `TableTransformer` (Inkonsistenz?, evtl. darauf hinweisen?)~~
  * For now I would favor #72 to reduce duplication of docstrings and make them easier to keep updated. Once #72 is done, we can no longer change `TableTransformer` to `OneHotEncoder` (@lars-reimann )

**Comment by lars-reimann** [comment]
I've created individual issues and linked them in the opening post.
