### ISSUE TITLE
Suggest similar columns if column gets accessed that doesn't exist

### ISSUE THREAD

**Issue by lars-reimann** [Safe-DS/Stdlib#203]
### Is your feature request related to a problem?

Sometimes people just mistype a column name.

### Desired solution

* We should see whether a column with a similar name exists in the current `Table` and include this in the error message ("did you mean XY"). To compute similarity of column names, use [`levenshtein`](https://pypi.org/project/Levenshtein/).

### Additional Context (optional)

If a column with the given name has existed in the past (#328), we should show that instead of looking for columns with similar names.

**Comment by guenterk** [comment]
If a column with the given name has existed in the past (https://github.com/Safe-DS/Stdlib/issues/328), we should show that FIRST ("Column XYZ has been removed using METHOD.") AND still suggest columns with similar names, AFTERWARDS ("Or did you mean column XXZ?").

**Comment by robmeth** [comment]
we need #328 to include the columns that have been removed
