### ISSUE TITLE
Transform a `Column`

### ISSUE THREAD

**Issue by patrikguempel** [Safe-DS/Stdlib#255]
### Is your feature request related to a problem?

A `Table` can already be transformed by calling `transform_table` or `transform_column`. It would be nice to have this capability on a `Column` too.

### Desired solution

* Add a method `transform` to `Column`:

```py
class Column(Sequence[_T]):
    def transform(self, transformer: Callable[[_T], _O]) -> Column[_O]:
        ...
```

* Map `transformer` over the values of the column and collect the results
* As usual, it should not change the receiving instance but return a new `Column`.

### Additional Context (optional)

The `apply` function of `pandas` could be useful here.

**Comment by lars-reimann** [comment]
`Table` already has `transform_table` and `transform_column`. A `Row` has heterogeneous values, so I don't see much use for it. That leaves only a `transform` function for column, which would be a nice addition.
