### ISSUE TITLE
Custom error if number is out of bounds

### ISSUE THREAD

**Issue by lars-reimann** [Safe-DS/Stdlib#262]
### Is your feature request related to a problem?

We have several cases where we check that a number is in some interval. However, error messages vastly differ.

### Desired solution

* New error class `OutOfBoundsError` that inherits from `ValueError`
* The bounds and the actual value should be passed to the constructor as arguments
* The error message should then be build in the constructor and passed to the `super` constructor

**Comment by alex-senger** [comment]
The error doesn't seem to be useful. Need to discuss with customer.

**Comment by lars-reimann** [comment]
> The error doesn't seem to be useful. Need to discuss with customer.

What's the issue with it?

**Comment by lars-reimann** [comment]
How about something like this:

```py
class OutOfBoundsError:
   def __init__(self, actual: float, *, lower_bound: Bound | None = None, upper_bound: Bound | None = None):
        ...

class Bound(ABC):
    ...

class ClosedBound(Bound):
    def __init__(self, value: float):
        ...

class OpenBound(Bound):
    def __init__(self, value: float):
        ...
```

Usage:

```py
OutOfBoundsError(actual = 0.5, upper_bound = OpenBound(1))
```

**Comment by patrikguempel** [comment]
I just used value error in Image#blend, as soon as this error is implemented, it can be used there too
