### ISSUE TITLE
Add copy method for Tables

### ISSUE THREAD

**Issue by zzril** [Safe-DS/Stdlib#275]
### Is your feature request related to a problem?

The `Table` and `TaggedTable` classes should have a dedicated private `_copy()` method.
This method is helpful for tests (e.g. when we want to verify that a method does not change the original table).
Also, a manual copy mechanism is currently implemented in several places. All of these occurrences should be found and be replaced by the new `_copy()` method.

These methods will not be intended for use by the end user.

One can consider also adding a copy method to the `Row` and `Column` classes.

### Desired solution

Implement `_copy()` for `Table` and `TaggedTable`. Find occurrences of manual copying and replace to use the new method.

**Comment by lars-reimann** [comment]
Regarding the name: I'd vote for `_copy`.

**Comment by patrikguempel** [comment]
used a copy dummy in table#remove_row and table#remove_rows
