### ISSUE TITLE
Table.remove_columns(): Specify what happens when removing the last column, so the table gets empty

### ISSUE THREAD

**Issue by zzril** [Safe-DS/Stdlib#276]
### Is your feature request related to a problem?

When removing the only column in a 1-column-table, the `number_of_rows` property is set to 0. This behaviour should be documented in the `Table` class docstring as well as in the following methods: `Table.keep_only_columns`, `Table.remove_columns`, `Table.remove_columns_with_missing_values` and `Table.remove_columns_with_non_numerical_values`.

### Desired solution

* document the behaviour

**Comment by lars-reimann** [comment]
Might be related to #123. In general, an empty table should have row count 0, but some methods might not be able to work properly with an empty table.
