### ISSUE TITLE
Find edges in image

### ISSUE THREAD

**Issue by lars-reimann** [Safe-DS/Stdlib#288]
### Is your feature request related to a problem?

I'd like to be able to find the edges on an image.

### Desired solution

* Add method `find_edges` to `Image` that returns a new image containing the edges but leaves the original unchanged.
* In the body of the function, first convert the image to grayscale (#287)

**Comment by sibre28** [comment]
Blocked by #287

**Comment by sibre28** [comment]
Blocked by #369
