### ISSUE TITLE
Identifying the column_type when initializing the Column seems to not work

### ISSUE THREAD

**Issue by PhilipGutberlet** [Safe-DS/Stdlib#315]
### Describe the bug

When initializing a Column in the __init__ method, the ColumnType is setted by the from_numpy_data_type method. This method in column_type is using the np.dtime.kind function. In the test_has_missing_values test, Columns with numeric parameters / None are initialized, but the Columntype is detected as a String (which is wrong).

### To Reproduce

1. Go to test_has_missing_values
2.  Run the test including the print method 
3.  Look at the error message with the types printed out

### Expected behavior

Analyze the source code and try to find the reason for the bug.

**Comment by Marsmaennchen221** [comment]
Will be implemented in #322
