### ISSUE TITLE
Detected the true Columntypes when initializing Column or Table

### ISSUE THREAD

**Issue by PhilipGutberlet** [Safe-DS/Stdlib#322]
### Is your feature request related to a problem?

Based on bug #315

### Desired solution

Designing a new function that detectes the Columntype based on the Safe-DS column types. The function is called when a new Column or table is initialized.

**Type hierarchy:**

* Anything
  * RealNumber
    * Integer
  * Boolean
  * String

### Screenshots (optional)

![image](https://github.com/Safe-DS/Stdlib/assets/2501322/6df5ea92-8afd-42be-989e-34cb575d9908)

**Comment by Marsmaennchen221** [comment]
See #127
