### ISSUE TITLE
Enhance and expand tutorials

### ISSUE THREAD

**Issue by lars-reimann** [Safe-DS/Stdlib#330]
* New tutorial "Getting started":
  * Explain how to use the different parts of the library to solve the popular Titanic example. The data is already available in the repository under `docs/tutorials/data/titanic.csv`.
* Improve "Data Processing" tutorial:
  * How to use table transformers / invertible table transformers
  * How to transform a column with `transform_column`
  * Use Markdown headings so the table of contents is filled properly (see https://stdlib.safeds.com/en/stable/tutorials/data_visualization/)
* Improve "Data Visualization" tutorial:
  * Add explanatory text to the sections "Boxplot" and beyond
* Improve "Machine Learning" tutorial:
  * How to use metrics in general
  * Which metrics are available
  * What do the different metrics mean (formulas) and when should they be used
  * Also useful to explain things like confusion matrix, false/true positive/negatives. Refer to the glossary by @patrikguempel for more information.

**Comment by daniaHu** [comment]
Added a new tutorial `getting_started.ipynb` to `docs/tutorials` to get users to use safeds to reimplement the famous example of the titanic. In the tutorial the user will use the features age and travel_class to predict the survival of passengers. Throughout the tutorial, users will get familiar with:

-Creating a table from a csv File. 
-Using `OneHotEncoder` to transform columns.
-Creating a tagged table out of a table.
-Using `RandomForest` as a classification model.
-Predicting values using `predict` function.

Modified the tutorial `data_processing.ipynb` by adding examples to apply the following:

- Transforming table using `Imputer` using Constant(0) as strategy.
- Transforming table using `LabelEncoder`.
- Transforming table using `OneHotEncoder`.
- Transforming table using `RangeScaler`, using range 0.0-1.0.
- Transforming table using `StandardScaler`.
- Transforming using the function transform_column of the `Table`class.

**Comment by jxnior01** [comment]
Modified the `data_visualization.ipynb` tutorial in `docs/tutorials` with detailed explanations for users to achieve a more comprehensive view of the box plots, histograms, and scatter plot. The user will learn how to interpret table data with the help of  different column plots such as age, survived, parents/children.
So, the following sections of the tutorial were modified to achieve this: 

* High level overview of a `Box plot`.
* Box plot explanations of all numerical columns.
* Definition and basic information of a `Histogram`.
* Histogram explanations of all columns.
* Understanding a `Scatter plot` with the help of the age and fare columns.

Added a new section `Metrics` in `machine_learning.ipynb` tutorial. It detailly explains ML-metrics such as `Confusion Matrix`, `Accuracy`,  `F1-score`, `Precision`, and `Recall`. The user will understand how to better interpret a confusion matrix  and when to use the different metrics used to evaluate a machine learning model.
The following sub-sections were added:

* High level overview of `Machine Learning Metrics`
* The different components of every metric
* `Confusion Matrix`: Definition, example code and code Interpretation.
* `Accuracy`: Definition, example code and code Interpretation.
* `F1-score`: Definition, example code and code Interpretation.
* `Precision`: Definition, example code and code Interpretation.
* `Recall`: Definition, example code and code Interpretation.
* When to use each of these metrics.
