### ISSUE TITLE
Return if a datatype in a `schema` is nullable in `__str__`

### ISSUE THREAD

**Issue by alex-senger** [Safe-DS/Stdlib#331]
### Is your feature request related to a problem?

When printing a `schema` it only shows the datatypes and column names. It should also print if the datatype is nullable.

### Desired solution

Add the value of nullable to the return string in the `__str__` method of `Schema`.

**Comment by lars-reimann** [comment]
I'd suggest to denote a nullable type with a question mark at the end, as done by Kotlin and the Safe-DS DSL for example. 

A nullable String would be `String?` for example.

**Comment by lars-reimann** [comment]
We need to check whether this is still an issue.
