### ISSUE TITLE
CodeCov would be reduced by current solution for issue #153

### ISSUE THREAD

**Issue by alex-senger** [Safe-DS/Stdlib#356]
In Issue #153 a few lines of code were commented out to keep CodeCov at 100%. These lines contain a try-catch block to catch a possible `LearningError` and `PredictionError` for errors that we already cover. It may be possible that we didn't cover every Error and these would still be thrown. We cannot think of a case and can't write tests for these as a consequence.

Either we remove these lines completely or we take into account that CodeCov is not at 100% anymore.

Link to the PR: #355

**Comment by zzril** [comment]
We could implement dummy models that ust always raise the required exception.  
E.g. a `ValueErrorOnFitClassifier` that will always raise a `ValueError` when calling `fit` (or `predict`) on it, then a `ValueErrorOnPredictClassifier` that only raises one when calling `predict` etc.

**Comment by Marsmaennchen221** [comment]
> We could implement dummy models that just always raise the required exception. E.g. a `ValueErrorOnFitClassifier` that will always raise a `ValueError` when calling `fit` (or `predict`) on it, then a `ValueErrorOnPredictClassifier` that only raises one when calling `predict` etc.
> 
> Then use one of those dummy models whenever we can't cover some line using the normal ones.

This solution will be implemented in #355 so this issue is irrelevant
