### ISSUE TITLE
Warnings raised by underlying `seaborn` and `numpy` libraries

### ISSUE THREAD

**Issue by zzril** [Safe-DS/Stdlib#357]
### Is your feature request related to a problem?

When running the test suite, currently 3 warnings will be raised from underlying libraries (`seaborn` and `numpy`) and are not catched.

These are the corresponding testcases:
* `tests/safeds/data/tabular/containers/_table/test_plot_correlation_heatmap.py::test_should_match_snapshot[empty]`
* `tests/safeds/data/tabular/containers/_table/test_plot_correlation_heatmap.py::test_should_match_snapshot[empty]`
* `tests/safeds/data/tabular/containers/_table/test_plot_histograms.py::test_should_match_snapshot[four columns]`

For the first 2, the warnings are raised by some `seaborn` module and seems to have the same cause, the 3rd one is some `numpy` thing.

### Desired solution

Ideal solution: Find the cause of the warnings and change the code to not produce these warnings anymore.

### Possible alternatives (optional)

If it's absolutely clear that we can't do anything to fix these warnings:  
Silence them in the code that produced them. (Not just in the tests!)

**Comment by lars-reimann** [comment]
We should configure Pytest to treat all warnings as errors (unless specifically ignored) in [pyproject.toml](https://github.com/Safe-DS/Stdlib/blob/6fc5289e25e5933d81ce52dcb1b9568134e622d5/pyproject.toml), as described [here](https://docs.pytest.org/en/7.1.x/how-to/capture-warnings.html).

**Comment by lars-reimann** [comment]
How to ignore warnings: https://github.com/Safe-DS/Stdlib/blob/c5d75df0c6a548eafe9caef291f0360b28a1d548/src/safeds/data/tabular/containers/_table.py#L1932-L1937

**Comment by zzril** [comment]
Updated the description to state that we donÄt just want to silence the warnings in the tests, but in the code that throws them.
