### ISSUE TITLE
Sorting of exceptions in `src/safeds/exceptions/__init.py__` not enforced by linter

### ISSUE THREAD

**Issue by zzril** [Safe-DS/Stdlib#370]
### Is your feature request related to a problem?

The exceptions in the `__all__` list in `src/safeds/exceptions/__init__.py` are currently (1752feb06bb5b0f041310956eca2ee5ed08dd999 on `main`) not sorted. Apparently, this is not enforced by the linter.

With the list not sorted, people will add new exceptions generally to the end of the list, producing unnecessary merge conflicts when different exceptions are added on different branches.  
With sorting enforced, merge conflicts would only happen when the new exceptions would come right after another in the alphabet (and thus would have to be inserted at the same position in the list).  
These merge conflicts are always trivial to resolve by hand, but it's still better to have git do that kind of work for us.

### Desired solution

Make the linter enforce that the list is sorted.

**Comment by lars-reimann** [comment]
Unfortunately, no Python linter seems to have a rule for this. Might be something to add to the [guidelines](https://stdlib.safeds.com/en/stable/development/guidelines/).

**Comment by Marsmaennchen221** [comment]
@PhilipGutberlet Please add the "Time spent by team" for your Issue

**Comment by zzril** [comment]
> Might be something to add to the [guidelines](https://stdlib.safeds.com/en/stable/development/guidelines/).

This part of the issue (adding it to the guidelines) will be covered by #427.
