### ISSUE TITLE
`UserWarning`s thrown in in test suite

### ISSUE THREAD

**Issue by zzril** [Safe-DS/Stdlib#399]
### Is your feature request related to a problem?

3 `UserWarning`s from `tests/safeds/data/tabular/transformation/test_imputer.py` and `.../_table_transformer.py` and `.../test_one_hot_encoder.py` are currently reported as not being catched by our test suite.
(Tested on 54a6040ab637605c766a722143fbcb8d6d0c8ccf.)

### Desired solution

Find the cause of the warnings and handle them accordingly.

If they're meant to be thrown, catch them in the tests.

Ideally, the linter should also be updated not not even allow the tests to pass with these uncatched warnings thrown (see #357).

**Comment by lars-reimann** [comment]
Small clarification: The warnings should be caught in the implementation and not just in the tests.

**Comment by zzril** [comment]
One of the warnings is the `OneHotEncoder` telling us that a column consisting of only `nan` values technically contains numerical data and thus does not really need to be one-hot-encoded.

I think the warning generally makes sense (although this case is somewhat pathologcal), so I would decide for just silencing it in the specific test that raised it.

---

The warning talking about "numerical" data (when in reality it's just `nan` values) might be confusing for some users, though.
Might want to think about detecting that specific case (all values in a colunm are `nan`) and raising a more specific / better-worded warning in that case.
