### ISSUE TITLE
Getting started guide for regression

### ISSUE THREAD

**Issue by lars-reimann** [Safe-DS/Stdlib#400]
Similar to the getting started guide for classification (based on the Titanic dataset, #330), we should have another getting started guide for regression (based on the House Sales dataset from [here](https://github.com/Safe-DS/Stdlib-Examples/blob/main/src/safeds_examples/tabular/_house_sales/data/house_sales.csv)). Copy the data to `docs/tutorials/data` and add another notebook using this data.

**Comment by zzril** [comment]
May want to change the name of the existing `Getting started` guide then.

Also, don't forget to add a link to the notebook file in `mkdocs.yml`, so it actually gets displayed on the docu page.
