### ISSUE TITLE
Add the ML metric `Mean Squared Error` to measure predictions made by a regression model

### ISSUE THREAD

**Issue by jxnior01** [Safe-DS/Stdlib#413]
### Is your feature request related to a problem?

Mean Squared Error (MSE) is a machine learning metric used to measure the average squared difference between predicted values and actual values in a regression problem.
It is used for evaluating model accuracy, penalizing large errors, and serving as a loss function during model training. 

### Desired solution

* Add MSE as a metric that would provide a quantitative measure of how well a regression model fits the data and aids in the selection and optimization of regression models.
* Verify that the new metric works as expected

**Comment by lars-reimann** [comment]
This exists already: https://github.com/Safe-DS/Stdlib/blob/main/src/safeds/ml/classical/regression/_regressor.py#L92
