### ISSUE TITLE
```drop_rows_with_outliers()``` currently not working

### ISSUE THREAD

**Issue by Gerhardsa0** [Safe-DS/Stdlib#7]
### Describe the bug

When calling the ```drop_rows_with_outliers```-function on ```Table```-object, the data in the table gets lost.

This failed on a large dataset(the titanic dataset).
### To Reproduce

1. create a ```Table```
2. call the ```Table.drop_rows_with_outliers()```-function
3. see that all the values of the table are missing

### Expected behavior

Only the outliers of the table should be removed

**Comment by lars-reimann** [comment]
This happens if any of the numerical columns has a missing value.
